name: CharSpreadsheet CI

on:
  push:
    paths:
      - 'datacalc.js'

jobs:
  getinfo:
    runs-on: ubuntu-latest
    outputs:
      textcontent: ${{ steps.get-string.outputs.tcontent }}
    steps:
    - name: Get String
      shell: bash
      working-directory: ./.github/workflows
      id: get-string
      run: echo "::set-output name=tcontent::$(node ./.github/workflows/get-string.js)"

  build:
    runs-on: ubuntu-latest
    needs: getinfo
    steps:
    - name: Write File
      uses: DamianReeves/write-file-action
      with:
        path: ./.github/workflows/out/exports.json
        contents: |
          echo ${{ needs.getinfo.outputs.textcontent }}
        write-mode: overwrite
