name: CharSpreadsheet CI

on:
  push:
    paths:
      - 'datacalc.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set Node Version
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'

    - name: Get String
      shell: bash
      id: get-string
      run: echo "::set-output name=textcontent::$(node ./.github/workflows/get-string.js)"

    - uses: actions/checkout@v2

    - name: Make file
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ./.github/workflows/out/exports.json
        contents: |
          echo "${{ steps.get-string.outputs.textcontent }}"
        write-mode: overwrite

    - name: Commit File
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic changes
        branch: master
        commit_options: '--no-verify --signoff'
        push_options: '--force'