name: CharSpreadsheet CI

on:
  push:
    paths:
      - 'datacalc.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set Node Version
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'

    - name: Get String
      shell: bash
      id: get-string
      run: echo "::set-output name=textcontent::$(node ./.github/workflows/get-string.js)"

    - uses: actions/checkout@v2

    - name: Patch File
      uses: onlyutkarsh/patch-files-action@v1.0.1
      with:
        files: ./.github/workflows/out/exports.json
        patch-syntax: |
          + /exports => "${{ steps.get-string.outputs.textcontent }}"
        fail-if-error: true

    - name: Commit File
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic changes
        branch: master
        commit_options: '--no-verify --signoff'
        file_pattern: datacalc.js
        push_options: '--force'